const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const tabs = await (await fetch('http://127.0.0.1:9227/json')).json();
  const socket = new WebSocket(tabs[0].webSocketDebuggerUrl);
  await new Promise(resolve => socket.addEventListener('open', resolve, {once:true}));
  let id = 0; const pending = new Map(); const errors = [];
  socket.addEventListener('message', event => {
    const message = JSON.parse(event.data);
    if (message.method === 'Runtime.exceptionThrown') errors.push(message.params);
    if (message.id) { const promise = pending.get(message.id); pending.delete(message.id); message.error ? promise.reject(message.error) : promise.resolve(message.result); }
  });
  const call = (method, params = {}) => new Promise((resolve, reject) => { const current = ++id; pending.set(current, {resolve,reject}); socket.send(JSON.stringify({id:current,method,params})); });
  const evaluate = async expression => {
    const response = await call('Runtime.evaluate', {expression, returnByValue:true, awaitPromise:true});
    if (response.exceptionDetails) throw new Error(JSON.stringify(response.exceptionDetails));
    return response.result.value;
  };
  const ready = () => evaluate(`new Promise(resolve => { const check=()=>document.querySelector('.topic') ? resolve(true) : setTimeout(check,30);check();})`);
  await call('Runtime.enable'); await call('Page.enable');
  await call('Page.bringToFront');
  await call('Emulation.setFocusEmulationEnabled', {enabled:true});
  await call('Emulation.setEmulatedMedia', {features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await call('Network.enable'); await call('Network.setCacheDisabled', {cacheDisabled:true});
  await call('Emulation.setDeviceMetricsOverride', {width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  await call('Page.navigate', {url:process.env.TASKFLOW_QA_URL || 'http://127.0.0.1:8080/'}); await ready();
  await evaluate('localStorage.clear(); location.reload();');
  await new Promise(resolve => setTimeout(resolve, 250)); await ready();
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`), 3);
  assert.equal(await evaluate(`document.querySelector('.sidebar-note') === null`), true);
  await evaluate(`document.querySelector('.topic-nav-item').click()`);
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`),1);
  await evaluate(`document.querySelector('.topic-nav-item').click()`);
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`),3);
  assert.equal(await evaluate(`document.querySelector('#add-topic') === null && document.querySelector('.heading-copy') === null`), true);
  assert.equal(await evaluate(`Number.parseFloat(getComputedStyle(document.querySelector('#today')).fontSize) >= 24`), true);
  assert.equal(await evaluate(`document.querySelector('[role=progressbar]').getAttribute('aria-valuenow')`), '20');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.stats')).gridTemplateColumns.split(' ').length`), 4);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('#topics')).gridTemplateColumns.split(' ').length`), 2);
  assert.equal(await evaluate(`Math.abs(document.querySelectorAll('.topic')[0].getBoundingClientRect().top - document.querySelectorAll('.topic')[1].getBoundingClientRect().top) < 2`), true);
  await evaluate(`document.querySelector('#bottom-add').click(); document.querySelector('#topic-name').value='테스트 주제'; document.querySelector('#topic-form').requestSubmit()`);
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`), 4);
  await evaluate(`const form=document.querySelector('.topic:last-child .task-form'); form.querySelector('input[type=text]').value='<img src=x onerror=alert(1)>'; form.querySelector('input[type=date]').value='2026-10-10';form.querySelector('input[type=date]').dispatchEvent(new Event('change'));form.requestSubmit()`);
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .todo-label').textContent`), '<img src=x onerror=alert(1)>');
  assert.equal(await evaluate(`document.querySelectorAll('.todo-label img').length`), 0);
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .due-badge').title`),'2026-10-10');
  await evaluate(`document.querySelector('.topic:last-child input[type=checkbox]').click()`);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.topic:last-child .todo-label')).textDecorationLine`), 'line-through');
  await evaluate(`document.querySelector('.topic:last-child .todo-edit').click(); const edit=document.querySelector('.topic:last-child .todo-row input[type=text]'); edit.value='수정한 할 일'; edit.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`);
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .todo-label').textContent`), '수정한 할 일');
  await evaluate(`document.querySelector('.topic:last-child .topic-icon').click(); [...document.querySelectorAll('.emoji-choice')].find(button=>button.textContent==='🎯').click();document.querySelector('#topic-form').requestSubmit()`);
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .topic-icon').textContent`), '🎯');
  await call('Page.reload'); await new Promise(resolve => setTimeout(resolve, 200)); await ready();
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .topic-icon').textContent`), '🎯');
  await evaluate(`document.querySelector('.topic:last-child .delete-todo').click();document.querySelector('#delete-dialog button[value=cancel]').click()`);
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .todo-label').textContent`), '수정한 할 일');
  await evaluate(`document.querySelector('.topic:last-child .delete-todo').click();document.querySelector('#delete-dialog button[value=confirm]').click()`);
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(await evaluate(`document.querySelector('.topic:last-child .todo-row') === null`), true);
  await evaluate(`document.querySelector('.topic:last-child .delete-topic').click();document.querySelector('#delete-dialog button[value=cancel]').click()`);
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`), 4);
  await evaluate(`document.querySelector('.topic:last-child .delete-topic').click();document.querySelector('#delete-dialog button[value=confirm]').click()`);
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`), 3);
  await call('Page.reload'); await new Promise(resolve => setTimeout(resolve, 200)); await ready();
  assert.equal(await evaluate(`document.querySelectorAll('.topic').length`), 3);
  await evaluate(`document.querySelector('[data-filter=done]').click()`);
  assert.equal(await evaluate(`document.querySelectorAll('.todo-row:not(.done)').length`), 0);
  await evaluate(`document.querySelector('[data-filter=all]').click(); const search=document.querySelector('#search');search.value='우선순위';search.dispatchEvent(new Event('input'))`);
  assert.equal(await evaluate(`document.querySelectorAll('.todo-row').length`), 1);
  await evaluate(`document.querySelector('#search').value='';document.querySelector('#search').dispatchEvent(new Event('input'));document.querySelector('.topic:first-child summary').click()`);
  await new Promise(resolve => setTimeout(resolve, 100));
  await call('Page.reload'); await new Promise(resolve => setTimeout(resolve, 200)); await ready();
  assert.equal(await evaluate(`document.querySelector('.topic:first-child').open`), false);
  assert.equal(await evaluate(`document.querySelector('.topic:first-child .todo-label').textContent`), '이번 주 우선순위 정리하기');
  await call('Emulation.setDeviceMetricsOverride', {width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert.equal(await evaluate(`document.documentElement.scrollWidth <= window.innerWidth`), true);
  fs.mkdirSync('artifacts', {recursive:true});
  let screenshot = await call('Page.captureScreenshot', {format:'png', captureBeyondViewport:true});
  fs.writeFileSync('artifacts/taskflow-mobile.png', Buffer.from(screenshot.data,'base64'));
  await evaluate(`localStorage.clear();location.reload()`); await new Promise(resolve => setTimeout(resolve, 200)); await ready();
  const originalTopics = await evaluate(`JSON.stringify(state.topics)`);
  await evaluate(`document.querySelector('#workspace-add').click();document.querySelector('#workspace-name').value='개인 공간';document.querySelectorAll('#workspace-emoji-picker button')[2].click();document.querySelector('#workspace-form').requestSubmit()`);
  assert.equal(await evaluate(`workspaceTopics().length`),0);
  assert.equal(await evaluate(`document.querySelector('#total').textContent`),'0개');
  assert.equal(await evaluate(`currentWorkspace().emoji`),'🌿');
  const workspaceId = await evaluate(`currentWorkspace().id`);
  await evaluate(`document.querySelector('#bottom-add').click();document.querySelector('#topic-name').value='개인 주제';document.querySelector('#topic-form').requestSubmit()`);
  assert.equal(await evaluate(`workspaceTopics().length`),1);
  await evaluate(`document.querySelector('#workspace-edit').click();document.querySelector('#workspace-name').value='개인 프로젝트';document.querySelectorAll('#workspace-emoji-picker button')[4].click();document.querySelector('#workspace-form').requestSubmit()`);
  assert.equal(await evaluate(`currentWorkspace().name`),'개인 프로젝트');
  assert.equal(await evaluate(`currentWorkspace().emoji`),'🎯');
  await evaluate(`document.querySelector('#workspace-select').value='default';document.querySelector('#workspace-select').dispatchEvent(new Event('change'))`);
  assert.equal(await evaluate(`JSON.stringify(workspaceTopics())`),originalTopics);
  await evaluate(`document.querySelector('#search').value='검색';document.querySelector('#search').dispatchEvent(new Event('input'));document.querySelector('#workspace-select').value=${JSON.stringify(workspaceId)};document.querySelector('#workspace-select').dispatchEvent(new Event('change'))`);
  assert.equal(await evaluate(`document.querySelector('#search').value`),'');
  assert.equal(await evaluate(`document.querySelector('.topic-title').textContent`),'개인 주제');
  await call('Page.reload');await new Promise(resolve=>setTimeout(resolve,250));await ready();
  assert.equal(await evaluate(`TaskStore.workspaces(state).length`),2);
  assert.equal(await evaluate(`currentWorkspace().id`),workspaceId);
  await evaluate(`document.querySelector('#workspace-select').value=${JSON.stringify(workspaceId)};document.querySelector('#workspace-select').dispatchEvent(new Event('change'));document.querySelector('#workspace-edit').click();document.querySelector('#workspace-delete').click();document.querySelector('#delete-dialog button[value=cancel]').click()`);
  await new Promise(resolve=>setTimeout(resolve,100));
  assert.equal(await evaluate(`TaskStore.workspaces(state).length`),2);
  await evaluate(`document.querySelector('#workspace-edit').click();document.querySelector('#workspace-delete').click();document.querySelector('#delete-dialog button[value=confirm]').click()`);
  await new Promise(resolve=>setTimeout(resolve,150));
  assert.equal(await evaluate(`TaskStore.workspaces(state).length`),1);
  assert.equal(await evaluate(`JSON.stringify(workspaceTopics())`),originalTopics);
  await evaluate(`document.querySelector('#workspace-edit').click();document.querySelector('#workspace-delete').click();document.querySelector('#delete-dialog button[value=confirm]').click()`);
  await new Promise(resolve=>setTimeout(resolve,150));
  assert.equal(await evaluate(`TaskStore.workspaces(state).length`),0);
  assert.equal(await evaluate(`document.querySelector('#workspace-select').disabled`),true);
  await evaluate(`document.querySelector('#workspace-add').click();document.querySelector('#workspace-name').value='다시 시작';document.querySelector('#workspace-form').requestSubmit()`);
  assert.equal(await evaluate(`TaskStore.workspaces(state).length`),1);
  assert.equal(await evaluate(`workspaceTopics().length`),0);
  await evaluate(`localStorage.clear();location.reload()`);await new Promise(resolve=>setTimeout(resolve,250));await ready();
  for (const [width,height] of [[320,568],[360,800],[375,667],[390,844],[393,852],[412,915],[430,932],[568,320],[844,390],[721,900],[768,1024],[900,700],[1050,800],[1440,1100],[1920,1080]]) {
    await call('Emulation.setDeviceMetricsOverride', {width,height,deviceScaleFactor:1,mobile:width<900});
    assert.equal(await evaluate(`(()=>{const logo=document.querySelector('.brand-icon'),vector=logo.querySelector('svg'),l=logo.getBoundingClientRect(),v=vector.getBoundingClientRect();if(vector.getAttribute('viewBox')!=='0 0 24 24'||logo.textContent.trim()||Math.abs(v.left+v.width/2-l.left-l.width/2)>.5||Math.abs(v.top+v.height/2-l.top-l.height/2)>.5)throw new Error('Logo vector alignment');return true})()`),true,`logo at ${width}`);
    assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`), true, `overflow at ${width}`);
    assert.equal(await evaluate(`getComputedStyle(document.querySelector('.stats')).gridTemplateColumns.split(' ').length`), 4);
    assert.equal(await evaluate(`(()=>{const cards=[...document.querySelectorAll('.stats>div')].map(card=>card.getBoundingClientRect());return cards.every(card=>Math.abs(card.top-cards[0].top)<1)})()`), true);
    assert.equal(await evaluate(`Number.parseFloat(getComputedStyle(document.querySelector('#today')).fontSize) >= 20`), true);
    assert.equal(await evaluate(`(()=>{const track=document.querySelector('.progress-track'),fill=document.querySelector('#overall-progress');return Math.abs(fill.getBoundingClientRect().width/track.getBoundingClientRect().width-.2)<.02})()`), true);
    assert.equal(await evaluate(`(()=>{return [...document.querySelectorAll('.stats>div')].every(card=>{const label=card.firstElementChild.getBoundingClientRect(),box=card.getBoundingClientRect();return label.right<=box.right-4&&label.left>=box.left})})()`), true, `stat label overflow at ${width}`);
    assert.equal(await evaluate(`(()=>{const box=document.querySelector('.workspace-selector').getBoundingClientRect(),aside=document.querySelector('.sidebar').getBoundingClientRect();if(box.width<=0||box.left<aside.left||box.right>aside.right||document.querySelector('#workspace-select').getBoundingClientRect().width<60)throw new Error('Workspace selector bounds');const before=box.top;const added=TaskStore.addWorkspace(state,'가'.repeat(60),'🎯');selectedWorkspace=added.id;render();if(Math.abs(document.querySelector('.workspace-selector').getBoundingClientRect().top-before)>.5||document.documentElement.scrollWidth>innerWidth)throw new Error('Workspace selector moved');state=TaskStore.initialState();selectedWorkspace='default';render();return true})()`),true,`workspace selector at ${width}`);
    assert.equal(await evaluate(`(()=>{if(document.querySelector('footer,.topbar,.list-heading')||document.querySelector('#workspace-edit').textContent.trim())throw new Error('Removed copy remains');const add=document.querySelector('#bottom-add'),a=add.getBoundingClientRect();if(a.width!==48||a.height!==48||getComputedStyle(add).borderRadius!=='50%'||!add.querySelector('svg'))throw new Error('Topic add circle');for(const form of document.querySelectorAll('.topic[open] .task-form')){const rects=[...form.children].map(e=>e.getBoundingClientRect()),middle=rects[1].top+rects[1].height/2;if(rects.some(r=>Math.abs(r.top+r.height/2-middle)>1)||form.scrollWidth>form.clientWidth||!form.querySelector('.calendar-control svg')||getComputedStyle(form.querySelector('input[type=date]')).opacity!=='0')throw new Error('Task input row');const plus=form.querySelector('.task-add-icon svg').getBoundingClientRect(),field=form.querySelector('input[type=text]').getBoundingClientRect();if(Math.abs(plus.top+plus.height/2-field.top-field.height/2)>.5)throw new Error('Task plus center');}if(Number(getComputedStyle(document.querySelector('.brand')).fontWeight)<700||getComputedStyle(document.querySelector('.brand')).fontFamily.indexOf('Arial')<0)throw new Error('Brand weight');return true})()`),true,`compact layout at ${width}`);
    assert.equal(await evaluate(`(()=>{if(document.querySelector('#all-topics,#nav-count')||document.querySelector('#workspace-dialog p'))throw new Error('Removed workspace copy');for(const editing of [true,false]){openWorkspaceDialog(editing?currentWorkspace():null);for(const name of ['나의 할 일','가'.repeat(60)]){document.querySelector('#workspace-name').value=name;const d=document.querySelector('#workspace-dialog'),buttons=[document.querySelector('#workspace-delete'),document.querySelector('#workspace-cancel'),d.querySelector('button[type=submit]')].filter(e=>!e.hidden).map(e=>e.getBoundingClientRect()),center=buttons[0].top+buttons[0].height/2;if(buttons.some(r=>Math.abs(r.top+r.height/2-center)>.5)||d.scrollWidth>d.clientWidth)throw new Error('Workspace actions not centered');}document.querySelector('#workspace-close').click();}return true})()`),true,`workspace dialog cases at ${width}`);
    assert.equal(await evaluate(`(()=>{const other=TaskStore.addWorkspace(state,'하늘색 공간','🌿');TaskStore.addWorkspace(state,'가'.repeat(60),'💼');render();document.querySelector('#workspace-select').click();const menu=document.querySelector('#workspace-menu'),bounds=menu.getBoundingClientRect();if(menu.hidden||bounds.left<0||bounds.right>innerWidth||bounds.top<0||bounds.bottom>innerHeight||menu.scrollWidth>menu.clientWidth||menu.querySelectorAll('[role=option]').length!==3||!menu.querySelector('[aria-selected=true] .workspace-option-check'))throw new Error('Workspace menu layout');menu.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));if(document.activeElement!==menu.lastElementChild)throw new Error('Workspace menu keyboard');menu.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));if(!menu.hidden||document.activeElement!==document.querySelector('#workspace-select'))throw new Error('Workspace menu escape');document.querySelector('#workspace-select').click();menu.querySelectorAll('[role=option]')[1].click();if(currentWorkspace().id!==other.id||workspaceTopics().length!==0||!menu.hidden)throw new Error('Workspace menu selection');document.querySelector('#workspace-select').click();document.body.dispatchEvent(new Event('pointerdown',{bubbles:true}));if(!menu.hidden)throw new Error('Workspace menu outside close');state=TaskStore.initialState();selectedWorkspace='default';render();return true})()`),true,`custom workspace menu at ${width}`);
    for (const message of ['이 브라우저에 저장됨', '모든 기기에 동기화됨', '서버 미저장 · 이 기기에 보관됨']) {
      await evaluate(`document.querySelector('#save-status').textContent=${JSON.stringify(message)};document.querySelector('#sync-now').hidden=${message==='이 브라우저에 저장됨'};document.querySelector('#account-button').textContent=${JSON.stringify(message==='이 브라우저에 저장됨'?'로그인':'나의 계정')}`);
      assert.equal(await evaluate(`(()=>{const header=document.querySelector('.app-header'),tools=document.querySelector('.account-tools'),status=document.querySelector('#save-status');const h=header.getBoundingClientRect(),t=tools.getBoundingClientRect(),s=status.getBoundingClientRect(),b=document.querySelector('.brand').getBoundingClientRect(),group=document.querySelector('.account-area').getBoundingClientRect(),edge=h.right-parseFloat(getComputedStyle(header).paddingRight);return Math.abs(t.right-edge)<1&&Math.abs((group.top+group.height/2)-(b.top+b.height/2))<1&&b.right<t.left&&Math.abs(s.right-edge)<1&&s.bottom<=t.top&&h.height===(innerWidth>720?77:85)&&document.documentElement.scrollWidth<=innerWidth})()`),true,`status alignment at ${width}: ${message}`);
    }
    await evaluate(`document.querySelector('#save-status').textContent='모든 기기에 동기화됨';document.querySelector('#sync-now').hidden=false;document.querySelector('#account-button').textContent='나의 계정'`);
    if ([320,390].includes(width)) {
      const preview = await call('Page.captureScreenshot', {format:'png',captureBeyondViewport:true});
      fs.writeFileSync(`artifacts/taskflow-stats-${width}.png`,Buffer.from(preview.data,'base64'));
    }
  }
  await evaluate(`document.querySelector('#save-status').textContent='이 브라우저에 저장됨';document.querySelector('#sync-now').hidden=true;document.querySelector('#account-button').textContent='로그인'`);
  await evaluate(`var originalLayoutState=JSON.parse(JSON.stringify(state));state.topics.forEach(topic=>topic.todos.forEach(todo=>todo.done=true));render()`);
  assert.equal(await evaluate(`document.querySelector('[role=progressbar]').getAttribute('aria-valuenow')`), '100');
  await evaluate(`state={version:1,topics:[]};render()`);
  assert.equal(await evaluate(`document.querySelector('[role=progressbar]').getAttribute('aria-valuenow')`), '0');
  await evaluate(`state=originalLayoutState;render()`);
  await call('Emulation.setDeviceMetricsOverride', {width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  await evaluate('window.scrollTo(0,0)');
  await new Promise(resolve => setTimeout(resolve, 100));
  screenshot = await call('Page.captureScreenshot', {format:'png',captureBeyondViewport:true});
  fs.writeFileSync('artifacts/taskflow-desktop.png',Buffer.from(screenshot.data,'base64'));
  assert.equal(errors.length, 0, JSON.stringify(errors));
  socket.close();
  console.log('Chrome QA passed: workspace creation, empty start, switching, rename, emoji, reload, deletion/cancellation, stable selector with long names, right-aligned guest/synced/offline header at 15 viewport sizes, four stats in one row, two-column topics, banner removal, emoji selection and persistence, deletion confirmation/cancellation and persistence, creation, escaping, completion, editing, filters, search, mobile layout, zero runtime errors.');
})().catch(error => { console.error(error);process.exit(1); });
