const assert = require('node:assert/strict');
require('../web/store.js');
const store = globalThis.TaskStore;
const memory = new Map();
const storage = { getItem: key => memory.has(key) ? memory.get(key) : null, setItem: (key, value) => memory.set(key, value) };
const state = store.load(storage);
assert.equal(state.topics.length, 3);
assert.ok(store.validate(state));
const topic = store.addTopic(state, '  개인 프로젝트  ');
assert.equal(topic.name, '개인 프로젝트');
assert.throws(() => store.addTopic(state, '  '));
assert.throws(() => store.addTopic(state, 'x'.repeat(61)));
store.addTodo(topic, '  웹 배포하기  ', '2026-10-10');
store.addTodo(topic, '<img src=x onerror=alert(1)>');
assert.equal(topic.todos[0].title, '웹 배포하기');
assert.throws(() => store.addTodo(topic, '  '));
assert.throws(() => store.addTodo(topic, 'x'.repeat(201)));
assert.throws(() => store.addTodo(topic, '잘못된 기한', 'tomorrow'));
assert.equal(store.visibleTodos(topic, 'pending', '').length, 2);
topic.todos[0].done = true;
assert.equal(store.visibleTodos(topic, 'done', '').length, 1);
assert.equal(store.visibleTodos(topic, 'all', '배포').length, 1);
assert.equal(store.visibleTodos(topic, 'all', '개인 프로젝트').length, 2);
assert.equal(store.visibleTodos(topic, 'pending', '배포').length, 0);
topic.open = false;
store.save(storage, state);
assert.deepEqual(store.load(storage), state);
const duplicate = JSON.parse(JSON.stringify(state));
duplicate.topics[1].id = duplicate.topics[0].id;
assert.equal(store.validate(duplicate), false);
storage.setItem(store.KEY, 'broken JSON');
assert.throws(() => store.load(storage));
assert.equal(storage.getItem(store.KEY), 'broken JSON');
storage.setItem(store.KEY, '{"version":1,"topics":[{}]}');
assert.throws(() => store.load(storage));
assert.throws(() => store.save({setItem(){throw new Error('quota');}}, state));
console.log('Workspace creation, validation, completion, filters, persistence and failure cases passed.');
