const assert = require('node:assert/strict');
require('../web/store.js');
const store = globalThis.TaskStore;
const memory = new Map();
const storage = { getItem: key => memory.has(key) ? memory.get(key) : null, setItem: (key, value) => memory.set(key, value) };
const state = store.load(storage);
assert.equal(state.topics.length, 3);
assert.ok(store.validate(state));
assert.equal(state.topics[0].emoji, undefined);
const emojiTopic = store.addTopic(state, '이모티콘 주제', '🎯');
assert.equal(emojiTopic.emoji, '🎯');
assert.throws(() => store.addTopic(state, '잘못된 이모티콘', 'unknown'));
store.addTodo(emojiTopic, '삭제할 할 일');
const deletedTodoId = emojiTopic.todos[0].id;
store.deleteTodo(emojiTopic, deletedTodoId);
assert.equal(emojiTopic.todos.length, 0);
assert.throws(() => store.deleteTodo(emojiTopic, deletedTodoId));
store.addTodo(emojiTopic, '주제와 함께 삭제할 할 일');
store.deleteTopic(state, emojiTopic.id);
assert.equal(state.topics.length, 3);
assert.throws(() => store.deleteTopic(state, emojiTopic.id));
const topic = store.addTopic(state, '  개인 프로젝트  ');
assert.equal(topic.name, '개인 프로젝트');
assert.throws(() => store.addTopic(state, '  '));
assert.throws(() => store.addTopic(state, 'x'.repeat(61)));
store.addTodo(topic, '  웹 배포하기  ', '2026-10-10');
store.addTodo(topic, '<img src=x onerror=alert(1)>');
assert.equal(topic.todos[0].title, '웹 배포하기');
assert.throws(() => store.addTodo(topic, '  '));
assert.throws(() => store.addTodo(topic, 'x'.repeat(201)));
assert.throws(() => store.addTodo(topic, '잘못된 기한', 'tomorrow'));
assert.equal(store.visibleTodos(topic, 'pending', '').length, 2);
topic.todos[0].done = true;
assert.equal(store.visibleTodos(topic, 'done', '').length, 1);
assert.equal(store.visibleTodos(topic, 'all', '배포').length, 1);
assert.equal(store.visibleTodos(topic, 'all', '개인 프로젝트').length, 2);
assert.equal(store.visibleTodos(topic, 'pending', '배포').length, 0);
topic.open = false;
store.save(storage, state);
assert.deepEqual(store.load(storage), state);
const duplicate = JSON.parse(JSON.stringify(state));
duplicate.topics[1].id = duplicate.topics[0].id;
assert.equal(store.validate(duplicate), false);
storage.setItem(store.KEY, 'broken JSON');
assert.throws(() => store.load(storage));
assert.equal(storage.getItem(store.KEY), 'broken JSON');
storage.setItem(store.KEY, '{"version":1,"topics":[{}]}');
assert.throws(() => store.load(storage));
assert.throws(() => store.save({setItem(){throw new Error('quota');}}, state));
const empty = {version: 1, topics: []};
store.save(storage, empty);
assert.deepEqual(store.load(storage), empty);
console.log('Workspace creation, validation, completion, filters, persistence and failure cases passed.');

const legacy = store.initialState(), original = JSON.parse(JSON.stringify(legacy.topics));
const first = store.workspaces(legacy)[0];
const newSpace = store.addWorkspace(legacy, '  개인 공간  ', '🌿');
assert.equal(newSpace.name, '개인 공간');
assert.deepEqual(newSpace.topics, []);
assert.deepEqual(legacy.workspaces[0].topics, original);
assert.deepEqual(legacy.topics, []);
store.addTopic(newSpace, '나만의 주제', '🎯');
assert.equal(legacy.workspaces[0].topics.length, 3);
store.editWorkspace(legacy, first.id, '업무', '💼');
store.save(storage, legacy);
assert.deepEqual(store.load(storage), legacy);
assert.throws(() => store.addWorkspace(legacy, ' ', '📋'));
assert.throws(() => store.editWorkspace(legacy, newSpace.id, 'a'.repeat(61), '📋'));
assert.throws(() => store.addWorkspace(legacy, '잘못된 이모티콘', 'x'));
const invalidSpaces = JSON.parse(JSON.stringify(legacy));
invalidSpaces.workspaces[1].id = invalidSpaces.workspaces[0].topics[0].id;
assert.equal(store.validate(invalidSpaces), false);
store.deleteWorkspace(legacy, first.id);
assert.equal(legacy.workspaces.length, 1);
assert.equal(legacy.workspaces[0].topics[0].name, '나만의 주제');
store.deleteWorkspace(legacy, newSpace.id);
assert.ok(store.validate(legacy));
assert.deepEqual(store.load({getItem: () => JSON.stringify(legacy)}).workspaces, []);
assert.throws(() => store.deleteWorkspace(legacy, newSpace.id));
console.log('Multiple workspaces passed: legacy preservation, empty creation, rename, emoji, isolation, persistence, deletion and invalid fields.');
